# Publish this app to npm
name: Publish to npm
on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public --//registry.npmjs.org/:_authToken=${{env.NODE_AUTH_TOKEN}}
